/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zs_test_jni_HiJni */
#include <android/log.h>

#ifndef _Included_com_zs_test_jni_HiJni
#define _Included_com_zs_test_jni_HiJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zs_test_jni_HiJni
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zs_test_jni_HiJni_sayHello
        (JNIEnv *, jobject);

// 调用java层的方法
int callJavaMethod(JNIEnv *env, jobject, jstring);

// 对应java的setNum方法
jint setNum(JNIEnv *env, jobject javaObj, jstring num);


#ifdef __cplusplus
}
#endif
#endif
